version: '2'  
services: 

  dockerapi:
    image: bobrik/socat
    ports:
      - "0.0.0.0:2375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: TCP-LISTEN:2375,reuseaddr,fork UNIX-CLIENT:/var/run/docker.sock

  gitmirror:
    build:
      context: ./git
      dockerfile: Dockerfile
      args:
        bfver: metadata54
        omerover: metadata53
    volumes:
      - ${PWD}/git/.gitconfig:/home/omero/.gitconfig
      - ./git/.ssh:/home/omero/.ssh
      - m2:/home/omero/.m2
      - workspace:/home/omero/workspace
      - src:/src
  ci:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    links:
      - dockerapi
      - db
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    volumes_from:
      - dockerapi
    extra_hosts:
      - "dockerapi:192.168.100.100"
    environment:
      - JENKINS_OPTS= --argumentsRealm.passwd.${JENKINS_USERNAME}=${JENKINS_PASSWORD} --argumentsRealm.roles.${JENKINS_USERNAME}=admin

  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  redis:
    image: redis

volumes:
  src:
    driver: local
  m2:
    driver: local
  workspace:
    driver: local
